apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lma15q0ha-go
  janus-idp.io/tekton: lma15q0ha-go
  backstage.io/kubernetes-id: lma15q0ha-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lma15q0ha-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
